# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-17 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_import', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=512)),
                ('district', models.CharField(max_length=512)),
                ('scenesid', models.CharField(max_length=512)),
                ('scenesname', models.CharField(max_length=512)),
                ('parentscenes', models.CharField(max_length=512)),
                ('scenesdescription', models.CharField(max_length=3000)),
                ('scenesrange', models.CharField(max_length=3000)),
                ('sceneslon', models.FloatField(blank=True, null=True)),
                ('sceneslat', models.FloatField(blank=True, null=True)),
                ('firstscenes', models.CharField(max_length=512)),
                ('secondscenes', models.CharField(max_length=512)),
                ('hotregion', models.CharField(max_length=512)),
                ('vitalarea', models.CharField(max_length=512)),
                ('population', models.FloatField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('cell2g', models.CharField(max_length=512)),
                ('cell3g', models.CharField(max_length=512)),
                ('cell4g', models.CharField(max_length=512)),
                ('carrier2g', models.CharField(max_length=512)),
                ('carrier3g', models.CharField(max_length=512)),
                ('carrier4g', models.CharField(max_length=512)),
                ('fpoint2g', models.CharField(max_length=512)),
                ('fpoint3g', models.CharField(max_length=512)),
                ('fpoint4g', models.CharField(max_length=512)),
                ('mobilecover2g', models.CharField(max_length=512)),
                ('mobilecover3g', models.CharField(max_length=512)),
                ('mobilecover4g', models.CharField(max_length=512)),
                ('mobilefpoint', models.CharField(max_length=512)),
                ('telecomcover2g', models.CharField(max_length=512)),
                ('telecomcover3g', models.CharField(max_length=512)),
                ('telecomcover4g', models.CharField(max_length=512)),
                ('telecomfpoint', models.CharField(max_length=512)),
                ('sceneslevel', models.CharField(max_length=512)),
                ('customize1', models.CharField(max_length=512)),
                ('customize2', models.CharField(max_length=512)),
            ],
        ),
    ]
