# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-17 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_import', '0002_scenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gsmcell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellname', models.CharField(max_length=512)),
                ('lac', models.CharField(max_length=512)),
                ('ci', models.CharField(max_length=512)),
                ('nodebname', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=512)),
                ('totalstations', models.CharField(max_length=512)),
                ('physicalstationname', models.CharField(max_length=512)),
                ('physicalstationid', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Wcdmacell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellname', models.CharField(max_length=512)),
                ('lac', models.CharField(max_length=512)),
                ('ci', models.CharField(max_length=512)),
                ('nodebname', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=512)),
                ('totalstations', models.CharField(max_length=512)),
                ('physicalstationname', models.CharField(max_length=512)),
                ('physicalstationid', models.CharField(max_length=512)),
            ],
        ),
    ]
