# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_import', '0003_gsmcell_wcdmacell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cellunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
