# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-17 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_import', '0004_ltecell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gsmcellindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellname', models.CharField(max_length=512)),
                ('lac', models.CharField(max_length=512)),
                ('ci', models.CharField(max_length=512)),
                ('nodebname', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=512)),
                ('tchflow', models.FloatField(blank=True, null=True)),
                ('resource_usage', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ltecellindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellname', models.CharField(max_length=512)),
                ('lac', models.CharField(max_length=512)),
                ('ci', models.CharField(max_length=512)),
                ('nodebname', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=512)),
                ('upflow', models.FloatField(blank=True, null=True)),
                ('downflow', models.FloatField(blank=True, null=True)),
                ('resource_usage', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wcdmacellindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellname', models.CharField(max_length=512)),
                ('lac', models.CharField(max_length=512)),
                ('ci', models.CharField(max_length=512)),
                ('nodebname', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=512)),
                ('csflow', models.FloatField(blank=True, null=True)),
                ('upflow', models.FloatField(blank=True, null=True)),
                ('downflow', models.FloatField(blank=True, null=True)),
                ('resource_usage', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
