# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_import', '0005_gsmcellindex_ltecellindex_wcdmacellindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cellunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
